### ISSUE TITLE
Hello!

### ISSUE THREAD

**Issue by thesoldiersway** [codrops/StickySections#1]
A big thanks again for this fantastic work! You are always amazing. 

Just a question. How can I disable Lenis? I have scrollsmoother gsap. I tried to trick with the index.js and erased the Lenis lines but the effects not working without. Is there a workaround if I will use gsap smooth? Lenis is a very nice free alternate to gsap smooth I will just try it with gsap. 

I am a big fan of you and my next question is'; what should I do without you and Codrops? It is a retoric question :-) All best to you!

**Comment by botelho** [comment]
Thanks for your message. Commenting initSmoothScroll at index.js works for me. Can you try that and confirm? Thanks

**Comment by thesoldiersway** [comment]
Thank you :-) Nothing wrong with the Lenis smooth scroll, it´s working well. I am just curious how it will work with gsap smooth. I check it. Thanks again <3

**Comment by thesoldiersway** [comment]
Yes it´s worked like a charm! Thank you and all my best wishes!
